services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_etl
    restart: always
    environment:
      SA_PASSWORD: "StrongPass123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - external_network
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 30s && 
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'StrongPass123!' -i /docker-entrypoint-initdb.d/init-db.sql &&
      wait
      "

volumes:
  sql_data:
    driver: local

networks:
  external_network:
    external: true
